{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "In an attempt to build an AI-ready workforce, Microsoft announced Intelligent Cloud Hub which has been launched to empower the next generation of students with AI-ready skills\n",
      "Envisioned as a three-year collaborative program, Intelligent Cloud Hub will support around 100 institutions with AI infrastructure, course content and curriculum, developer support, development tools and give students access to cloud and AI services\n",
      "As part of the program, the Redmond giant which wants to expand its reach and is planning to build a strong developer ecosystem in India with the program will set up the core AI infrastructure and IoT Hub for the selected campuses\n",
      "The company will provide AI development tools and Azure AI services such as Microsoft Cognitive Services, Bot Services and Azure Machine Learning.According to Manish Prakash, Country General Manager-PS, Health and Education, Microsoft India, said, \"With AI being the defining technology of our time, it is transforming lives and industry and the jobs of tomorrow will require a different skillset\n",
      "This will require more collaborations and training and working with AI\n",
      "Thatâ€™s why it has become more critical than ever for educational institutions to integrate new cloud and AI technologies\n",
      "The program is an attempt to ramp up the institutional set-up and build capabilities among the educators to educate the workforce of tomorrow.\" The program aims to build up the cognitive skills and in-depth understanding of developing intelligent cloud connected solutions for applications across industry\n",
      "Earlier in April this year, the company announced Microsoft Professional Program In AI as a learning track open to the public\n",
      "The program was developed to provide job ready skills to programmers who wanted to hone their skills in AI and data science with a series of online courses which featured hands-on labs and expert instructors as well\n",
      "This program also included developer-focused AI school that provided a bunch of assets to help build AI skills.\n",
      "Indexes of top r_sent order are  [(0.15083257041122708, ['Envisioned', 'as', 'a', 'three-year', 'collaborative', 'program,', 'Intelligent', 'Cloud', 'Hub', 'will', 'support', 'around', '100', 'institutions', 'with', 'AI', 'infrastructure,', 'course', 'content', 'and', 'curriculum,', 'developer', 'support,', 'development', 'tools', 'and', 'give', 'students', 'access', 'to', 'cloud', 'and', 'AI', 'services']), (0.13161201335715553, ['The', 'company', 'will', 'provide', 'AI', 'development', 'tools', 'and', 'Azure', 'AI', 'services', 'such', 'as', 'Microsoft', 'Cognitive', 'Services,', 'Bot', 'Services', 'and', 'Azure', 'Machine', 'Learning.According', 'to', 'Manish', 'Prakash,', 'Country', 'General', 'Manager-PS,', 'Health', 'and', 'Education,', 'Microsoft', 'India,', 'said,', '\"With', 'AI', 'being', 'the', 'defining', 'technology', 'of', 'our', 'time,', 'it', 'is', 'transforming', 'lives', 'and', 'industry', 'and', 'the', 'jobs', 'of', 'tomorrow', 'will', 'require', 'a', 'different', 'skillset']), (0.11403047674961146, ['Earlier', 'in', 'April', 'this', 'year,', 'the', 'company', 'announced', 'Microsoft', 'Professional', 'Program', 'In', 'AI', 'as', 'a', 'learning', 'track', 'open', 'to', 'the', 'public']), (0.10721749759953528, ['In', 'an', 'attempt', 'to', 'build', 'an', 'AI-ready', 'workforce,', 'Microsoft', 'announced', 'Intelligent', 'Cloud', 'Hub', 'which', 'has', 'been', 'launched', 'to', 'empower', 'the', 'next', 'generation', 'of', 'students', 'with', 'AI-ready', 'skills']), (0.10404298514456578, ['As', 'part', 'of', 'the', 'program,', 'the', 'Redmond', 'giant', 'which', 'wants', 'to', 'expand', 'its', 'reach', 'and', 'is', 'planning', 'to', 'build', 'a', 'strong', 'developer', 'ecosystem', 'in', 'India', 'with', 'the', 'program', 'will', 'set', 'up', 'the', 'core', 'AI', 'infrastructure', 'and', 'IoT', 'Hub', 'for', 'the', 'selected', 'campuses']), (0.10031366655994461, ['Thatâ€™s', 'why', 'it', 'has', 'become', 'more', 'critical', 'than', 'ever', 'for', 'educational', 'institutions', 'to', 'integrate', 'new', 'cloud', 'and', 'AI', 'technologies']), (0.10001137283486655, ['The', 'program', 'is', 'an', 'attempt', 'to', 'ramp', 'up', 'the', 'institutional', 'set-up', 'and', 'build', 'capabilities', 'among', 'the', 'educators', 'to', 'educate', 'the', 'workforce', 'of', 'tomorrow.\"', 'The', 'program', 'aims', 'to', 'build', 'up', 'the', 'cognitive', 'skills', 'and', 'in-depth', 'understanding', 'of', 'developing', 'intelligent', 'cloud', 'connected', 'solutions', 'for', 'applications', 'across', 'industry']), (0.09916750119894317, ['This', 'will', 'require', 'more', 'collaborations', 'and', 'training', 'and', 'working', 'with', 'AI']), (0.09277191614415067, ['The', 'program', 'was', 'developed', 'to', 'provide', 'job', 'ready', 'skills', 'to', 'programmers', 'who', 'wanted', 'to', 'hone', 'their', 'skills', 'in', 'AI', 'and', 'data', 'science', 'with', 'a', 'series', 'of', 'online', 'courses', 'which', 'featured', 'hands-on', 'labs', 'and', 'expert', 'instructors', 'as', 'well'])]\n",
      "Summary of the Article: \n",
      " Envisioned as a three-year collaborative program, Intelligent Cloud Hub will support around 100 institutions with AI infrastructure, course content and curriculum, developer support, development tools and give students access to cloud and AI services. The company will provide AI development tools and Azure AI services such as Microsoft Cognitive Services, Bot Services and Azure Machine Learning.According to Manish Prakash, Country General Manager-PS, Health and Education, Microsoft India, said, \"With AI being the defining technology of our time, it is transforming lives and industry and the jobs of tomorrow will require a different skillset\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[nltk_data] Downloading package stopwords to\n",
      "[nltk_data]     C:\\Users\\sahil.c\\AppData\\Roaming\\nltk_data...\n",
      "[nltk_data]   Package stopwords is already up-to-date!\n"
     ]
    }
   ],
   "source": [
    "#Sahil.C : imnotsahil@gmail.com, Sweety : ssweety9643@gmail.com, Mohit Porwal : porwalmohit1999@gmail.com.\n",
    "#TEAM ID- 1961----\n",
    "#Analyticscosm internship ----Competition ID AC01----\n",
    "#Natural Language Processing to Summarize NEWS----\n",
    "#Approach Used - Extractive Summarization Technique\n",
    "#Team Contribution:\n",
    "#-----------------\n",
    "#- Sweety : ssweety9643@gmail.com : \n",
    "#  suggesting approach to be used,importing libraries, initialization,coding checking sentence similarity function\n",
    "#------------------------------------------------------------------------------------------------------------------\n",
    "#- Sahil.C : imnotsahil@gmail.com (Team Leader) :\n",
    "#  coding create summary function, debugging, clearing errors,checking for alternative approaches ,co-ordinating\n",
    "#------------------------------------------------------------------------------------------------------------------\n",
    "#- Mohit Porwal : porwalmohit1999@gmail.com :\n",
    "#  coding creating similarity matrix, reviewing code , creating input repository to test the code, testing\n",
    "#------------------------------------------------------------------------------------------------------------------\n",
    "\n",
    "#!/usr/bin/env python\n",
    "# coding: utf-8\n",
    "#importing libraries\n",
    "import nltk\n",
    "from nltk.corpus import stopwords\n",
    "from nltk.cluster.util import cosine_distance\n",
    "import numpy as np\n",
    "import networkx as nx\n",
    "\n",
    "#functiom to read the articles that need to be summarized\n",
    "def read_file(fname):\n",
    "    file = open(fname, \"r\")\n",
    "    fdata = file.readlines()\n",
    "    article = fdata[0].split(\". \")\n",
    "    sents = []\n",
    "\n",
    "    for sentence in article:\n",
    "        print(sentence)\n",
    "        sents.append(sentence.replace(\"[^a-zA-Z]\", \" \").split(\" \"))\n",
    "    sents.pop() \n",
    "    \n",
    "    return sents\n",
    "#function for checking sentence similarity\n",
    "def _checking_sentence_similarity(sent1, sent2, stopwords=None):\n",
    "    if stopwords is None:\n",
    "        stopwords = []\n",
    "    \n",
    "    sent1 = [w.lower() for w in sent1]\n",
    "    sent2 = [w.lower() for w in sent2]\n",
    " \n",
    "    w_all = list(set(sent1 + sent2))\n",
    " \n",
    "    #creating vectors\n",
    "    v1 = [0] * len(w_all)\n",
    "    v2 = [0] * len(w_all)\n",
    " \n",
    "    # building the vector for the first sentence\n",
    "    for w in sent1:\n",
    "        if w in stopwords:\n",
    "            continue\n",
    "        v1[w_all.index(w)] += 1\n",
    " \n",
    "    # building the vector for the second sentence\n",
    "    for w in sent2:\n",
    "        if w in stopwords:\n",
    "            continue\n",
    "        v2[w_all.index(w)] += 1\n",
    " \n",
    "    return 1 - cosine_distance(v1, v2)#returning cosine _distance vector\n",
    "\n",
    "\n",
    "#function to build the similarity matrix of the article \n",
    "def create_s_matrix(sents, stop_words):\n",
    "    # Create an empty similarity matrix\n",
    "    s_matrix = np.zeros((len(sents), len(sents)))\n",
    " \n",
    "    for idx1 in range(len(sents)):\n",
    "        for idx2 in range(len(sents)):\n",
    "            if idx1 == idx2: #ignore if both are same sents\n",
    "                continue \n",
    "            s_matrix[idx1][idx2] = _checking_sentence_similarity(sents[idx1], sents[idx2], stop_words)\n",
    "\n",
    "    return s_matrix #returning the similarity matrix\n",
    "\n",
    "\n",
    "#function to create summary\n",
    "def create_summary(fname, top_n=5):\n",
    "    nltk.download(\"stopwords\")\n",
    "    stop_words = stopwords.words('english')\n",
    "    s_text = []\n",
    "\n",
    "    #reading the input text from the article and splitting\n",
    "    sents =  read_file(fname)\n",
    "\n",
    "    #creating a similarity matrix for all the sents of the input text\n",
    "    _checking_sentence_similarity_martix = create_s_matrix(sents, stop_words)\n",
    "\n",
    "    #ranking the sents from the similarity matrix\n",
    "    _checking_sentence_similarity_graph = nx.from_numpy_array(_checking_sentence_similarity_martix)\n",
    "    scores = nx.pagerank(_checking_sentence_similarity_graph)\n",
    "\n",
    "    #picking the top ranked sentence from the sinilarity matrix\n",
    "    r_sent = sorted(((scores[i],s) for i,s in enumerate(sents)), reverse=True)    \n",
    "    print(\"Indexes of top r_sent order are \", r_sent)    \n",
    "    \n",
    "    #looping and appending ranked sents to the summary\n",
    "    #thus generating a summary of the article\n",
    "    for i in range(top_n):\n",
    "      s_text.append(\" \".join(r_sent[i][1]))\n",
    "\n",
    "    #printing the output of the input article\n",
    "    print(\"Summary of the Article: \\n\", \". \".join(s_text))\n",
    "\n",
    "#calling the create summary function to create summary of the specified article\n",
    "create_summary( \"msft.txt\", 2)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
